### ISSUE TITLE
"EFI variables are not supported on this system." Any workarounds for on the Pop OS btrfs guide?

### ISSUE THREAD

**Issue by GrapeJamMan** [wmutschl/mutschler.dev#5]
Page: https://mutschler.dev/linux/pop-os-btrfs-22-04/

Following this guide to get pretty much everything I want to play with in one go, but when I get to the finish line of the system setup, update-initramfs -c -k all, the output does not look good. (this is not a missing comma issue)

```
root@pop-os:/# update-initramfs -c -k all
update-initramfs: Generating /boot/initrd.img-6.0.2-76060002-generic
kernelstub.Config    : INFO     Looking for configuration...
EFI variables are not supported on this system.
kernelstub.NVRAM     : ERROR    Failed to retrieve NVRAM data. Are you running in a chroot?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kernelstub/nvram.py", line 55, in get_nvram
    return subprocess.check_output(command).decode('UTF-8').split('\n')
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/sudo', 'efibootmgr']' returned non-zero exit status 2.
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 22.04
    Root partition:....../dev/dm-1
    Root FS UUID:........9f457238-56d6-4ef4-80d7-7f0ecbb4d788
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash rootflags=subvol=@
    Kernel Image Path:.../boot/vmlinuz-6.0.2-76060002-generic
    Initrd Image Path:.../boot/initrd.img-6.0.2-76060002-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     No old kernel found, skipping
```

Where I had to differ from the guide was that I don't have sda for my storage device, instead of comes over as /dev/nvme0n1 (nvme0n1p1, nvme0n1p2, etc), but I would hope that didn't make a difference because the output does show ESP Partition correctly.

Any help would really be appreciated, I've never messed with anything other than what defaults distributions give me for installs so this is brand new stuff for me and I'd like to really understand what's going on.

**Comment by awebeer256** [comment]
I had this issue too and I found a fix.

In the command that creates bind mounts for the `chroot` environment, add one more path to the list: `/sys/firmware/efi/efivars`. So instead of this:
```
for i in /dev /dev/pts /proc /sys /run; do mount -B $i /mnt$i; done
```
you do this:
```
for i in /dev /dev/pts /proc /sys /sys/firmware/efi/efivars /run; do mount -B $i /mnt$i; done
```
Source: https://unix.stackexchange.com/questions/91620/#418913

**Comment by wmutschl** [comment]
Thank you for the fix! Looks like it helped other people on YouTube as well! Good Job!
